[build]
target = "xtensa-esp32-espidf"
[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash --monitor /dev/cu.usbserial-110"

[unstable]

build-std = ["std", "panic_abort"]

[env]
ESP_IDF_VERSION = { value = "branch:release/v4.4" }
[package.metadata.esp-idf-sys]
esp_idf_tools_install_dir = "global"
